// DO NOT EDIT THIS FILE
// DO NOT EDIT THIS FILE
import 'package:flutterquiz/core/config/config.dart';

export 'api_body_parameter_labels.dart';
export 'api_endpoints_constants.dart';
export 'assets_constants.dart';
export 'error_message_keys.dart';
export 'fonts.dart';
export 'hive_constants.dart';
export 'sound_constants.dart';
export 'string_labels.dart';

const kAppName = appName;
const kPackageName = packageName;

const kMaxPhoneNumberLength = maxPhoneNumberLength;

//lifelines
const fiftyFifty = 'fiftyFifty';
const audiencePoll = 'audiencePoll';
const skip = 'skip';
const resetTime = 'resetTime';

//firestore collection names
const battleRoomCollection = 'battleRoom';
const multiUserBattleRoomCollection = 'multiUserBattleRoom';
const messagesCollection = 'messages';

const inBetweenQuestionTimeInSeconds = 1;

//predefined messages for battle
const kPredefinedMessages = predefinedMessages;

//constants for badges and rewards
const minimumQuestionsForBadges = 5;

const kExamRules = examRules;

List<String> payoutRequestNotes(
  String payoutRequestCurrency,
  String amount,
  String coins,
) {
  return payoutRequestNote(payoutRequestCurrency, amount, coins);
}

final kPayoutMethods = payoutMethods;
